# Generated by Django 3.2.11 on 2022-01-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_detail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('pro_detail', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('productrelation', models.ManyToManyField(to='product.CategoryTable')),
            ],
        ),
    ]
