# Generated by Django 3.2.11 on 2022-01-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='image',
            field=models.ImageField(default='', upload_to='ironshop/image'),
        ),
        migrations.AddField(
            model_name='playlists',
            name='list_price',
            field=models.IntegerField(default=0),
        ),
    ]
