# Generated by Django 3.2.11 on 2022-01-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tutoriallist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_name', models.CharField(max_length=50)),
                ('tutorial_catgry', models.CharField(max_length=50)),
                ('tutorial_price', models.IntegerField(default=0)),
                ('tutorial_detail', models.CharField(max_length=200)),
            ],
        ),
    ]
