# Generated by Django 3.2.11 on 2022-01-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyRegisterUser',
        ),
    ]
