# Generated by Django 3.2.11 on 2022-01-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firstapp', '0002_delete_myregisteruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mystudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('scholornum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Myteacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serialno', models.IntegerField(default=0)),
            ],
        ),
    ]
